Repository appsignal/appsignal-status, pull requests merged in 2021-09, with the labels that each got.

#14 Status updates
  components/StatusIcon/StatusIcon.js
  components/StatusIcon/StatusIcon.test.js
  components/StatusIcon/__snapshots__/StatusIcon.test.js.snap
  components/StatusUpdate/StatusUpdate.js
  components/StatusUpdate/StatusUpdate.test.js
  components/StatusUpdate/__snapshots__/StatusUpdate.test.js.snap
  components/StatusUpdates/StatusUpdate.js
  components/StatusUpdates/StatusUpdates.js
  components/StatusUpdates/StatusUpdates.test.js
  components/StatusUpdates/__snapshots__/StatusUpdates.test.js.snap
  mocks/status_pages/appsignal.json
  pages/index.js
Labels: choree

#15 Remove get in touch and render page title
  components/Header/Header.js
  components/Header/Header.test.js
  components/Header/__snapshots__/Header.test.js.snap
  pages/index.js
Labels: choree

#16 Implement currentStatus
  components/CurrentStatus/CurrentStatus.js
  components/CurrentStatus/CurrentStatus.test.js
  pages/index.js
Labels: choree

#21 Render proper loading state
  components/UptimeMonitor/UptimeMonitor.js
  components/UptimeMonitor/UptimeMonitor.test.js
  components/UptimeMonitor/__snapshots__/UptimeMonitor.test.js.snap
  components/UptimeMonitors/__snapshots__/UptimeMonitors.test.js.snap
Labels: choree

#19 Fix scrolling in overlay
  components/OutagesOverlay/OutagesOverlay.js
Labels: choree

#23 Add 404 page
  components/Footer/Footer.js
  components/Footer/__snapshots__/Footer.test.js.snap
  pages/404.js
Labels: enhancement

#26 Add purge CSS
  .env.development
  package.json
  postcss.config.js
  yarn.lock
Labels: choree

#27 Add delay to tippy
  components/UptimeDot/UptimeDot.js
  components/UptimeDot/UptimeDot.test.js
Labels: choree

#28 render Missing data points
  components/UptimeDot/UptimeDot.js
  components/UptimeDot/UptimeDot.test.js
  components/UptimeDots/UptimeDots.js
  components/UptimeDots/UptimeDots.test.js
  components/UptimeDots/__snapshots__/UptimeDots.test.js.snap
  mocks/monitors/homepage.json
  package.json
  pages/_app.js
  utils/index.js
  utils/index.test.js
  yarn.lock
Labels: choree

#29 Check if all regions are present
  components/Outages/Outages.js
  components/Outages/Outages.test.js
  components/UptimeDots/UptimeDots.js
  components/UptimeDots/UptimeDots.test.js
  components/UptimeDots/__snapshots__/UptimeDots.test.js.snap
  components/UptimeMonitor/UptimeMonitor.js
  mocks/monitors/homepage.json
  utils/index.js
  utils/index.test.js
Labels: choree

#31 Only render a downtime if it's below the specified threshold
  components/UptimeDot/UptimeDot.js
  components/UptimeDot/UptimeDot.test.js
  components/UptimeDots/UptimeDots.js
  components/UptimeDots/UptimeDots.test.js
  components/UptimeDots/__snapshots__/UptimeDots.test.js.snap
  components/UptimeMonitor/UptimeMonitor.js
  components/UptimeMonitor/UptimeMonitor.test.js
  components/UptimeMonitors/UptimeMonitors.js
  mocks/status_pages/appsignal.json
Labels: feature
